######################################################################
# Automatically generated by qmake (3.0) jeu. mars 10 11:22:22 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += tst_testprojecttest.moc
SOURCES += tst_testprojecttest.cpp
