######################################################################
# Automatically generated by qmake (3.0) jeu. mars 10 11:32:12 2016
######################################################################

QT += gui widgets
TEMPLATE = app
TARGET = TERM1-WebCreator
INCLUDEPATH += . src

# Input
HEADERS += ui_mainwindow.h src/mainwindow.h
FORMS += src/mainwindow.ui
SOURCES += src/main.cpp src/mainwindow.cpp
