######################################################################
# Automatically generated by qmake (3.0) jeu. mars 10 11:13:42 2016
######################################################################

TEMPLATE = app
TARGET = TERM1-WebCreator
INCLUDEPATH += . src

# Input
HEADERS += src/mainwindow.h
FORMS += src/mainwindow.ui
SOURCES += src/main.cpp src/mainwindow.cpp
